### ISSUE TITLE
Simplify exports

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nsymbols#1]
@aartaka You've used a bunch of `(export ... :nsymbols)`.  The `:nsymbols` seems redundant, isn't it?

**Comment by aartaka** [comment]
No, it's not. Given that `define-symbol-type` is used in packages other than `:nsymbols`, we have to be extremely careful to not accidentally intern anything into the package that uses `define-symbol-type`. Thus the obligatory `:nsymbols` export.

**Comment by aartaka** [comment]
Ahhh, right.
