### ISSUE TITLE
define-symbol-type ambiguity

### ISSUE THREAD

**Issue by Ambrevar** [atlas-engineer/nsymbols#2]
The readme says

> creates a type FUNCTION that will 

but it does not create a `function` type (which already exists in CL), it creates a "symbol type", right?  Maybe underline the nuance here.

**Comment by aartaka** [comment]
Well, I thought of a better word for this, like "symbol kind" or "symbol type", but hasn't found any better than type.

**Comment by Ambrevar** [comment]
I find both examples better than just "type" :)

**Comment by aartaka** [comment]
b6addee8c72fb23fde4001457c2f1da45455cd80 should fix it.

**Comment by Ambrevar** [comment]
Thanks!
