### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by aadcg** [atlas-engineer/nsymbols#6]
When running the tests locally, one of them fails. 

This is because `(nsymbols:package-functions :nsymbols :internal)` expects to returns 2, but 8 are returned:

```lisp
(NSYMBOLS::PACKAGE-GENERIC-FUNCTIONS*
 NSYMBOLS::PACKAGE-FUNCTIONS*
 NSYMBOLS::DESIGNATOR NSYMBOLS::RESULTS
 NSYMBOLS::PACKAGE-CLASSES*
 NSYMBOLS::PACKAGE-STRUCTURES*
 NSYMBOLS::PACKAGE-METHODS*
 NSYMBOLS::PACKAGE-SLOTS*)
```

When starting with a clean Lisp image, calling `(nsymbols:package-functions :nsymbols :internal)` returns `(NSYMBOLS::RESULTS NSYMBOLS::DESIGNATOR)`. Upon issuing `(asdf:load-system :nsymbols)`, 8 are returned.

**Comment by aartaka** [comment]
It seems that you loaded `nsymbols/star` before running the tests. I'll add a guard against it.

**Comment by aartaka** [comment]
Right! So the solution is rather to remove `nsymbols/star` from `nsymbols/tests/compilation`.

**Comment by aartaka** [comment]
Yes.
